/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Ventana;

/**
 *
 * @author Marianghel
 */
public class FRM_Ventana extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Ventana
     */
    Controlador_FRM_Ventana controlador;
    public FRM_Ventana() {
        initComponents();
   controlador=new Controlador_FRM_Ventana(this);
        this.setLocationRelativeTo(null);
        this.rbn_Normal.setSelected(true);
        agregarEventos(controlador);
    }
    
    public void agregarEventos( Controlador_FRM_Ventana controlador){
        this.controlador=controlador;
        this.btn_MayorMenor.addActionListener(controlador);
        this.btn_MenorMayor.addActionListener(controlador);
        this.btn_Registrar.addActionListener(controlador);
        this.btn_Siguiente.addActionListener(controlador);
        this.btn_Cancelar.addActionListener(controlador); 
        this.btn_Modificar.addActionListener(controlador);
    }
      public void mensaje() {
        String mensaje = "Opcion elegida:";
        if (rbn_7600.isSelected()) {
            mensaje = mensaje + "Cliente 7600";
        }
        if (rbn_Normal.isSelected()) {
            mensaje = mensaje + "Cliente normal";
        }
       
       jl_Mensaje.setText(mensaje);
    }
     
     public boolean opcionPrioridad(){
        boolean esPrioridad=false;
       if (rbn_7600.isSelected()) {
           esPrioridad=true;
        }
        if (rbn_Normal.isSelected()) {
            esPrioridad=false;
        }  
        return esPrioridad;
     }

     public void setArea(String informacion){
         this.jta_Reporte.setText(informacion);
     }
     public void setJt_Cedula(String cedula){
         this.jt_Cedula.setText(cedula);
     }
     public String getJt_Cedula(){
         return this.jt_Cedula.getText();
     }
      public String getJt_NombreCompleto(){
         return this.jt_NombreC.getText();
     }
       public String getJt_Edad(){
         return this.jt_Edad.getText();
     }
     public void mostrarFecha(String fecha){
         this.jt_Fecha.setText(fecha);
     }
     public String getJt_Fecha(){
         return this.jt_Fecha.getText();
     }
      public void setJt_NombreLlamado(String nombreLlamado){
        this.jt_LlamadoCliente.setText(nombreLlamado);
   } 
      public String getJt_CancelarCedula(){
        return  this.jt_CedulaEliminar.getText();
      }
      
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jt_NombreC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jt_Edad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jt_Fecha = new javax.swing.JTextField();
        rbn_Normal = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rbn_7600 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        btn_Siguiente = new javax.swing.JButton();
        jt_LlamadoCliente = new javax.swing.JTextField();
        btn_Registrar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jt_CedulaEliminar = new javax.swing.JTextField();
        btn_Cancelar = new javax.swing.JButton();
        jta_Reporte = new java.awt.TextArea();
        label1 = new java.awt.Label();
        btn_MayorMenor = new javax.swing.JButton();
        btn_MenorMayor = new javax.swing.JButton();
        jl_Mensaje = new javax.swing.JLabel();
        btn_Modificar = new javax.swing.JButton();
        btn_CantidadP = new javax.swing.JButton();
        btn_Informacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Departamento de migración");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Entrega de pasaportes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 70, -1, -1));

        jLabel3.setText("Cédula");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        getContentPane().add(jt_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, 30));

        jLabel4.setText("Nombre completo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        getContentPane().add(jt_NombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 230, 30));

        jLabel5.setText("Edad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        getContentPane().add(jt_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 50, 30));

        jLabel6.setText("Asignación de fecha");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jt_Fecha.setEditable(false);
        getContentPane().add(jt_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 120, 30));

        buttonGroup1.add(rbn_Normal);
        rbn_Normal.setText("Normal");
        getContentPane().add(rbn_Normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Prioridad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        buttonGroup1.add(rbn_7600);
        rbn_7600.setText("7600");
        getContentPane().add(rbn_7600, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 740, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Siguiente Cliente");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 110, 20));

        btn_Siguiente.setText("Siguiente");
        getContentPane().add(btn_Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 90, 30));

        jt_LlamadoCliente.setEditable(false);
        getContentPane().add(jt_LlamadoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 270, 30));

        btn_Registrar.setText("Registrar Nueva Cita");
        btn_Registrar.setActionCommand("Registrar");
        getContentPane().add(btn_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 150, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 740, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Cancelar cita");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, -1));

        jLabel10.setText("Cédula ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, -1, -1));
        getContentPane().add(jt_CedulaEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, 190, 30));

        btn_Cancelar.setText("Cancelar cita");
        btn_Cancelar.setActionCommand("Cancelar");
        getContentPane().add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 640, 110, 30));
        getContentPane().add(jta_Reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 290, 300));

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Reportes");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, 20));

        btn_MayorMenor.setText("Mayor-menor");
        getContentPane().add(btn_MayorMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 110, 30));

        btn_MenorMayor.setText("Menor-mayor");
        getContentPane().add(btn_MenorMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 110, 30));

        jl_Mensaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jl_Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 270, 30));

        btn_Modificar.setText("Modificar datos");
        getContentPane().add(btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 140, 30));

        btn_CantidadP.setText("Cantidad fila");
        getContentPane().add(btn_CantidadP, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 110, 30));

        btn_Informacion.setText("Información");
        getContentPane().add(btn_Informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_CantidadP;
    private javax.swing.JButton btn_Informacion;
    private javax.swing.JButton btn_MayorMenor;
    private javax.swing.JButton btn_MenorMayor;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JButton btn_Registrar;
    private javax.swing.JButton btn_Siguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jl_Mensaje;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_CedulaEliminar;
    private javax.swing.JTextField jt_Edad;
    private javax.swing.JTextField jt_Fecha;
    private javax.swing.JTextField jt_LlamadoCliente;
    private javax.swing.JTextField jt_NombreC;
    private java.awt.TextArea jta_Reporte;
    private java.awt.Label label1;
    private javax.swing.JRadioButton rbn_7600;
    private javax.swing.JRadioButton rbn_Normal;
    // End of variables declaration//GEN-END:variables
}
